// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import Foundation

class ImagePickerTestImages: NSObject {
  @objc static var jpgTestData: Data {
    let bundle = Bundle(for: self)
    if let url = bundle.url(forResource: "jpgImage", withExtension: "jpg"),
      let data = try? Data(contentsOf: url) {
      return data
    }
    let base64 = [
      "/9j/4AAQSkZJRgABAQAASABIAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAA",
      "AABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAA",
      "AAAQAAAAygAwAEAAAAAQAAAAcAAAAA/8AAEQgABwAMAwERAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQ",
      "YHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGB",
      "kaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpq",
      "eoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAA",
      "AAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFW",
      "Jy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJ",
      "WWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAAgICAg",
      "ICAwICAwUDAwMFBgUFBQUGCAYGBgYGCAoICAgICAgKCgoKCgoKCgwMDAwMDA4ODg4ODw8PDw8PDw8PD//bAEMBAgMDBA",
      "QEBwQEBxALCQsQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEP/dAAQAAv/aAA",
      "wDAQACEQMRAD8A9S8ZfsFeG/sH/IUboe7V/JHgR4t4v+2/4XVdj908aPHLG/2P/B6PsfO5/YL8O7m/4mjdT3av966fi1i",
      "vZw/ddF2P8VZ+OeN9pP8Ac9X2P//Z"
    ].joined()
    return Data(base64Encoded: base64)!
  }

  @objc static var jpgTallTestData: Data {
    let bundle = Bundle(for: self)
    if let url = bundle.url(forResource: "jpgImageTall", withExtension: "jpg"),
      let data = try? Data(contentsOf: url) {
      return data
    }
    let base64 = [
      "/9j/4AAQSkZJRgABAQAAAAAAAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJD",
      "RENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB",
      "AQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAHAAQDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABP/EAB0QAAE",
      "CBwAAAAAAAAAAAAAAAAIABgQIFiVBQlH/xAAUAQEAAAAAAAAAAAAAAAAAAAAH/8QAHBEAAQQDAQAAAAAAAAAAAAAABAA",
      "HI1EIFlIX/9oADAMBAAIRAxEAPwA76kLbdSxV/PGxcTHjm7hXngUfVWgp+n0N3suLmqX/2Q=="
    ].joined()
    return Data(base64Encoded: base64)!
  }

  @objc static var pngTestData: Data {
    let bundle = Bundle(for: self)
    if let url = bundle.url(forResource: "pngImage", withExtension: "png"),
      let data = try? Data(contentsOf: url) {
      return data
    }
    let base64 = [
      "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAHEAIAAADjQOcwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAA",
      "CA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAhGVYSWZNTQAqAAAACAAFARIAAwAAAAEAAQAAARoABQAAAAEAAABKARsABQAA",
      "AAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAAEgAAAABAAAASAAAAAEAA6ABAAMAAAABAAEAAKACAAQAAA",
      "ABAAAADKADAAQAAAABAAAABwAAAACX5qZPAAAACXBIWXMAAAsTAAALEwEAmpwYAAACx2lUWHRYTUw6Y29tLmFkb2JlLnht",
      "cAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogIC",
      "A8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAg",
      "ICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYm",
      "UuY29tL3RpZmYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8i",
      "PgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6UmVzb2",
      "x1dGlvblVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+NzI8L3RpZmY6",
      "WFJlc29sdXRpb24+CiAgICAgCiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgIC",
      "AgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4xMjwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOkNv",
      "bG9yU3BhY2U+MTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+NzwvZXhpZjpQaX",
      "hlbFlEaW1lbnNpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgqm8Gvm",
      "AAAAUElEQVQYGWP4/58BCJDJV6sYGERD9wPFHRimhjIwZK3KAopMDXUAqtv/XxQoAlKBquf/fyaQEDUACwOD2W0qGeSlSi",
      "WDPFWoZBB1vEa1wAYAWgsa+7/A1uQAAAAASUVORK5CYII="
    ].joined()
    return Data(base64Encoded: base64)!
  }

  @objc static var gifTestData: Data {
    let bundle = Bundle(for: self)
    if let url = bundle.url(forResource: "gifImage", withExtension: "gif"),
      let data = try? Data(contentsOf: url) {
      return data
    }
    let base64 = [
      "R0lGODlhDAAHAPAAAOpCNQAAACH5BABkAAAAIf8LTkVUU0NBUEUyLjADAQAAACwAAAAADAAHAAACCISPqcvtD1UBACH5BA",
      "BkAAAALAAAAAAMAAcAhuc/JPA/K+49Ne4+PvA7MrhYHoB+A4N9BYh+BYZ+E4xyG496HZJ8F5J4GaRtE6tsH7tWIr9SK7xV",
      "KJl3IKpvI7lrKc1FLc5PLNJILsdTJMFVJsZWJshWIM9XIshWJNBWLd1SK9BUMNFRNOlAI+9CMuNJMetHPnuCAF66F1u8FV",
      "u7GV27HGytG3utGH6rHGK1G3WxFWeuIHqlIG60IGi4JTnTDzjZDy/VEy/eFTnVEDzXFxflABfjBRPmBRbnBxPrABvpARnt",
      "AxLuCBXuCQTyAAb1BgvwACnmDSPpDSLjECPpEDHhFFDLGIeAFoiBFoqCF4uCHYWnHJGVJqSNJQAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAdWgAIXCjE3PTtAPDUuByQfCzQ4Qj9BPjktBgAcCStJRURGQzYwJyMdDDM6SkhHS0xRCA",
      "EgD1IsKikoLzJTDgQlEBQNT05NUBMVBQMmGCEZHhsaEhEiFoEAIfkEAGQAAAAsAAAAAAwABwCFB+8ACewACu0ACe4ACO8A",
      "C+4ACu8ADOwAD+wAEOYAEekAA/EABfAAB/IAAfUAA/UAAPcAAfcAAvYAA/cBBPQABfUABvQAB/UBBvYBCfAACPEAC/AACv",
      "IACvMBAPgAAPkAAPgBAPkBAvgBAPoAAPoBAPPsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkfAAadjeUxEEYnk8QBoLhUHCASJ",
      "JCWLyiTiIZFG3lAoO4F4SiUwScywYCQQ8ScEEokCG06D8pA4mBUWCQoIBwIGGQQGBgUFQQA7"
    ].joined()
    return Data(base64Encoded: base64)!
  }
}
